### ISSUE TITLE
Move to PythonOptimizers organization?

### ISSUE THREAD

**Issue by dpo** [PythonOptimizers/pysparse#2]
@syarra
@counterclocker

**Comment by ghost** [comment]
I don't know. Isn't CySparse supposed to replace PySparse?

**Comment by dpo** [comment]
It is but so far nlp.py still supports PySparse.

**Comment by ghost** [comment]
Then you probably should update nlp.py, no?

**Comment by dpo** [comment]
You mean remove pysparse support?

**Comment by ghost** [comment]
Yes, this is what I mean.

**Comment by dpo** [comment]
It's not that easy to remove pysparse. For now I'll transition this to PythonOptimizers. At least, it will be with the rest of the Python packages.
